version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    container_name: postgres-container
    ports:
      - '5432:5432'
    volumes:
      - ./data_postgres:/var/lib/postgres

    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=app

  mysql:
    image: mysql:8.0.18
    container_name: mysql-container
    ports:
      - '3306:3306'
    volumes:
      - ./data_mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  node-app:
    build: .
    ports:
      - '9999:9999'